### ISSUE TITLE
option for output-only

### ISSUE THREAD

**Issue by GitzJoey** [autoNumeric/vue-autoNumeric#11]
i think its a great features to implement some kind output-only
not only for the input text by  using autoNumeric.format()

**Comment by GitzJoey** [comment]
let say we only need to show the value but already formatted
something like <p><vue-autonumeric v-model="somenumber"></vue-autonumeric></p>
and we see already formatted according to the config (eg $ 123.00 where somenumber = 123)

**Comment by AlexandreBonneau** [comment]
*I fixed your comment to use the correct html notation*

I'm still not sure exactly what you want, but from what I understood, it seems you can achieve the 'display only a non-interactive formatted value' just by either:
- using vue-autoNumeric with the `:tag="'p'"` prop and the `:options="{ readOnly: true, noEventListeners: true }"
- just create a custom component and just use `mounted() { this.value = AutoNumeric.format(val, options); }`

**Comment by GitzJoey** [comment]
ahh yes....that's perfect. case closed.
