### ISSUE TITLE
build fails on linux

### ISSUE THREAD

**Issue by markRosenvinge** [autoNumeric/vue-autoNumeric#16]
The recent change made in build/webpack.base.js creates a issue when compiling with webpack on case sensitive OS like linux.

```Javascript
This dependency was not found:

* AutoNumeric in ./node_modules/vue-autonumeric/dist/vue-autonumeric.min.js
```

THIS 
```Javascript
externals: {
    autonumeric: 'AutoNumeric',
```

SHOULD BE THIS
```Javascript
externals: {
    AutoNumeric: 'autonumeric',
```

**Comment by AlexandreBonneau** [comment]
Somehow, it seems when I unstashed some changes it overwrote the `build/webpack.base.js` configuration file.
Thanks for noticing @markRosenvinge.

I'll have one day to find a way to test that to prevent further regression.

**Comment by AlexandreBonneau** [comment]
Well, I ran the exact same tests than in issue #4 (creating `VueAutonum` and `VueAutonum3` projects to compile a dummy one with webpack 2 and 3), and cannot find any issue.
I also created a third project to test with the lastest webpack version (`v4.8.1` today), and the build works as expected.

I'm exclusively running Linux, so I think I would have spot any case sensitive issue!

Would you have a reproducible test case?

**Comment by AlexandreBonneau** [comment]
I modified the `webpack.config.js` yet again, and I cannot reproduce any error in the test projects I set up.
This should be fixed in `v1.2.3`.

Please reopen this issue if the problem should arise again.

**Comment by OLibutzki** [comment]
I stumbled upon the same issue using 1.2.6... with 1.2.3 it works flawlessly... so there seems to be a regression.

**Comment by antogkou** [comment]
Same bug in Linux for me. version 1.2.6 using a laravel and vue2 project. works great on my mac locally but fails on a linux container.

**Comment by esamani77** [comment]
> Same bug in Linux for me. version 1.2.6 using a laravel and vue2 project. works great on my mac locally but fails on a linux container.
 When I use `npm install vue-autonumeric`, Same bug appears on mac local.
 ‍‍`Module build failed: Error: ENOENT: no such file or directory, open '/Users/Desktop/project/src/node_modules/vue-autonumeric/dist/vue-autonumeric.min.js'`

**Comment by antogkou** [comment]
> > Same bug in Linux for me. version 1.2.6 using a laravel and vue2 project. works great on my mac locally but fails on a linux container.
> > When I use `npm install vue-autonumeric`, Same bug appears on mac local.
> > ‍‍`Module build failed: Error: ENOENT: no such file or directory, open '/Users/Desktop/project/src/node_modules/vue-autonumeric/dist/vue-autonumeric.min.js'`

Your error seems a bit different, this is what I get:
`ERROR in ./node_modules/vue-autonumeric/dist/vue-autonumeric.min.js Module not found: Error: Can't resolve 'AutoNumeric' in 'node_modules/vue-autonumeric/dist'`

**Comment by danjdewhurst** [comment]
Getting this on a Laravel 8 project, running `npm i` on a linux machine.

```
ERROR in ./node_modules/vue-autonumeric/dist/vue-autonumeric.min.js 1:82-104
Module not found: Error: Can't resolve 'AutoNumeric' in '/home/stagingportal/node_modules/vue-autonumeric/dist'
```

**Comment by phuhd-0935** [comment]
I got a error: "Cannot find module 'AutoNumeric' from 'vue-autonumeric.min.js'"
Does everyone have a solution for this?
