### ISSUE TITLE
unformatOnSubmit is not triggered when using submit.prevent

### ISSUE THREAD

**Issue by GitzJoey** [autoNumeric/vue-autoNumeric#17]
```html
<form id="poForm" method="post" v-on:submit.prevent="validateBeforeSubmit">
<vue-autonumeric type="text" name="item_quantity" v-model="quantity" v-bind:options="{unformatOnSubmit: true}"></vue-autonumeric>
</form>
```

in vue

```js
validateBeforeSubmit: function () {
var test = new FormData($('#poForm')[0]);
console.log(test.get('item_quantity'));
}
```
the console will print the formatted value not the unformatted value
why i need this because i need to send the name attribute as axios params to be sent to php controller

**Comment by AlexandreBonneau** [comment]
Using `submit.prevent`, you are effectively preventing the 'submit' event to be propagated, which means AutoNumeric does not get the chance to catch it, and cannot know it has to unformat anything.

You will have to unformat yourself in your `validateBeforeSubmit()` function.
You can use `formArrayNumericString()` or `formJsonNumericString()` as you see fit if you just want to retrieve the unformatted values, or just `formUnformat()` if you actually want the form input to display an unformatted value.

Hope that helps.


*Note: you do not need to declare `type="text"` on the `<vue-autonumeric>` element; it's added automatically if the tag is an `input` (which is the default)*
