### ISSUE TITLE
Problem when importing `vue-autonumeric`, but not when importing `AutoNumeric`

### ISSUE THREAD

**Issue by j-a-m-l** [autoNumeric/vue-autoNumeric#25]
I'm trying to use `vue-autonumeric` on an Electron app (on Linux).

I can import `autonumeric` alone
```js
import AutoNumeric from 'AutoNumeric'
````
using an alias:
```js
resolve: {
  alias: {
    'AutoNumeric': 'numeric'
  }
}
```

but if I try to import `vue-autonumeric` I see the error `Cannot find module 'AutoNumeric'`
```js
import VueAutonumeric from 'vue-autonumeric'
````
using an alias:
```js
resolve: {
  alias: {
     'AutoNumeric': 'numeric',
    // Or these other aliases
    // 'AutoNumeric': 'node_modules/autonumeric/dist/autoNumeric.min',
    // 'AutoNumeric': path.join(__dirname, '../node_modules/autonumeric/dist/autoNumeric.min'),
  }
}
```

**Comment by AlexandreBonneau** [comment]
Hi, this is the intended behavior as [pointed out in the doc](https://github.com/autoNumeric/vue-autoNumeric#installation):
> *Note: In order to minimize the size of the vue-autoNumeric component, the AutoNumeric library dependency is not bundled with it.*

We let the dev uses whatever AutoNumeric version he wishes, which indeed means you'll have to import it one way or another, either using a CDN, or [installing it](https://github.com/autoNumeric/vue-autoNumeric#or-by-importing-it-directly-as-an-es6-module) via `npm` beforehand.

Have you tried this configuration?:
```js
resolve: {
    alias: {
        AutoNumeric: 'node_modules/autonumeric/dist/autoNumeric.min',
    },
},
```

**Comment by j-a-m-l** [comment]
Yes, I tried it, but it wasn't able to find the module.

Since I finally decide to make a DIY solution (an input that, when isn't focused, use a different library to format the numeric content) and it's working fine, the issue could be closed.

Anyway, I appreciate your reply.

**Comment by j-a-m-l** [comment]
Well, isn't really a hack, but an "alternative implementation" ;-). In fact, it has something that I miss from this library: the ability to use locale codes, like `en-GB`, `es-ES`, etc.

**Comment by AlexandreBonneau** [comment]
@j-a-m-l this is interesting, would you please elaborate in a feature request in the AutoNumeric [issue tracker](https://github.com/autoNumeric/autoNumeric/issues/new)?

**Comment by j-a-m-l** [comment]
Done: https://github.com/autoNumeric/autoNumeric/issues/614
