### ISSUE TITLE
Add support for Nuxt

### ISSUE THREAD

**Issue by lgoudriaan** [autoNumeric/vue-autoNumeric#31]
I am getting a 'window is not defined' error so I can't use this library :(

**Comment by jesusalive** [comment]
You should add the plugin in nuxt.config.js and disable the ssr

NUXT CONFIG EXAMPLE
`
  plugins: [
    { src: '~/plugins/vue-agile' },
    { src: '~/plugins/vue-js-modal' },
    { src: '~/plugins/vue-mask', ssr: false },
    { src: '~/plugins/vue-lightbox', ssr: false },
    { src: '~/plugins/vue-observe-visibility', ssr: false },
    { src: '~/plugins/vue-carousel', ssr: false },
    { src: '~/plugins/vue-treeselect', ssr: false },
    { src: '~/plugins/vuex-persistedstate', ssr: false },
    { src: '~/plugins/vue-credit-card', ssr: false },
    { src: '~/plugins/vue-pusher', ssr: false },
    { src: '~/plugins/utils' },
    { src: '~/plugins/slide-menu', ssr: false },
    { src: '~/plugins/vue-screen-resize', ssr: false },
    { src: '~/plugins/vue-trend', ssr: false }
  ],
`

PLUGIN EXAMPLE
>>> vue-agile.js
`
import Vue from 'vue'
import VueAgile from 'vue-agile'

Vue.use(VueAgile)

`
