### ISSUE TITLE
Set value to zero after null

### ISSUE THREAD

**Issue by Zettex** [autoNumeric/vue-autoNumeric#33]
Hello.
I have a problem displaying a zero value after `null`.
null is not displayed in the input, but if I change the value to 0, it also does not appear...
Maybe I'm doing something wrong?
Or is there a way to avoid this problem?

Example https://codepen.io/Zeroox/pen/mddyerR

This has been fixed with a workaround by setting the value to '0'... But I think this is not good.

**Comment by AlexandreBonneau** [comment]
This is indeed a weird behavior here, since setting the value as `0` should work as expected.

For info, I've updated [your example](https://codepen.io/AnotherLinuxUser/pen/MWWYXOv?editors=1011) with few more tests.
