### ISSUE TITLE
Could I use with `Element UI Input`?

### ISSUE THREAD

**Issue by thearabbit** [autoNumeric/vue-autoNumeric#7]
I base on `Element UI`.
Could use?

**Comment by AlexandreBonneau** [comment]
Hey @thearabbit , thanks for your interest in vue-autoNumeric, however I'm not sure to understand your issue.

Would you care to elaborate?

**Comment by AlexandreBonneau** [comment]
Without answers about this terse bug report, I'm closing this issue.
Feel free to reopen if needed.
